### ISSUE TITLE
关于用CVPR数据集训练问题

### ISSUE THREAD

**Issue by HenrySZP** [milely/SRN.Pytorch#3]
你好，我用你提供的链接中CVPR的数据集进行训练，可是画面一直卡在这
```total image:  7266164
   total image:  7266164
   sample_num: 227068
```
是因为数据太大还没有加载完吗？还是别的原因呢。
另外如果我想用自己的数据集训练（包含中文），数据要转成mdb格式吗？

**Comment by milely** [comment]
测试了一下，数据加载不会非常长的时间。因为第一次运行的时候会跑一次验证集，sample_num 代表的是验证集一共有多少个batch，看你验证集的轮次比较多，应该是在跑验证。训练中文，目前的数据加载器是通过lmdb加载，你可以修改dataloader部分，直接从原始图片进行加载，只是数据加载的效率不如lmdb加载

**Comment by HenrySZP** [comment]
> 测试了一下，数据加载不会非常长的时间。因为第一次运行的时候会跑一次验证集，sample_num 代表的是验证集一共有多少个batch，看你验证集的轮次比较多，应该是在跑验证。训练中文，目前的数据加载器是通过lmdb加载，你可以修改dataloader部分，直接从原始图片进行加载，只是数据加载的效率不如lmdb加载

**Comment by Henryplay** [comment]
> 测试了一下，数据加载不会非常长的时间。因为第一次运行的时候会跑一次验证集，sample_num 代表的是验证集一共有多少个batch，看你验证集的轮次比较多，应该是在跑验证。训练中文，目前的数据加载器是通过lmdb加载，你可以修改dataloader部分，直接从原始图片进行加载，只是数据加载的效率不如lmdb加载

谢谢你的回复，我尝试着重新写一个dataloader直接读取txt文件获取图片数据，毕竟mdb格式的文件咱也没有接触过。。
